##########################
### Main Config For CE ###
##########################
#
#Notes:
#    Do not use ' or " in messages as I have not yet added support for these icons.
#   - Do not remove any lines as that will throw errors
#   - This plugin only supports Minecraft color codes. Ex) &eHello World&7!
#       - Use this link for a list of the codes: https://wiki.ess3.net/mc/
#   - If you want a message to be blank, please leave it as ''
#   - This plugin supports player name place holders as %Player%
# If you receive an error when CE loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
###########################
Config:
####How far a player can be to register a chest in blocks
    MaxRegisterDistance: '7'
PluginPrefix: '&7[&1ChestEvent&7]&6>>'
Messages:
    NoPerms: '&cYou do not have permission to run that command.'
    
    Reload: '&aAll ChestEvent files are now reloaded!'
    
    OnlyPlayers: '&cOnly players can run this command'
    
    RegisterPrompt1: '&cPlease use the format /ce register <name> <cooldown> <ItemSet>'
    
    RegisterPrompt2: '&cPlease register an item set before a chest to avoid errors!'
    
    NotAnInt: '&cPlease use the format of &4/ce register <name> <cooldown> <ItemSet> &cwhere cooldown is an int.'
    
    TooFar: '&cYou need to be looking at a block at most %Distance& blocks away.'
    
    NotAChest: '&cYou need to be looking at a chest'
    
    ChestNameAlreadyUsed: '&cThe name &e%ChestName% &chas already been used. Please use a different name'
    
    LocationAlreadyUsed: '&cA chest has already been registered at that location, please try elsewhere.'
    
    NotRegisteredChest: '&cThat chest is not registered.'
    
    SuccessfulRegister: '&aCongrats, &e%ChestName% &ahas been registered'
    
    ItemsPrompt1: '&cPlease use the format of'
    
    ItemsPrompt2: '&c/ce items register/unregister/edit/view <ItemSetName>'
    
    SuccessfulItemUnregister: '&aItem Set &e%ItemSet% &ahas been unregistered!'
    
    
